# Generated by Django 3.0.8 on 2020-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200819_1659'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_memberships',
            field=models.ManyToManyField(to='subscriptions.Membership'),
        ),
    ]
