# Generated by Django 3.0.8 on 2020-08-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_course_allowed_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allowed_memberships',
        ),
    ]
