# Generated by Django 3.0.8 on 2020-08-25 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_course_allowed_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next_slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
