# Generated by Django 3.0.8 on 2020-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_lesson_next_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='next_slug',
            field=models.SlugField(null=True),
        ),
    ]
