# Generated by Django 3.0.8 on 2020-08-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
