# Generated by Django 3.0.8 on 2020-08-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20200812_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
