# Generated by Django 3.0.8 on 2020-08-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_course_allowed_memberships'),
        ('subscriptions', '0002_auto_20200819_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
